openapi: 3.0.3
info:
  title: Superhero
  description: Application to maintain superheroes
  contact:
    email: carlos.ventoso714@gmail.com
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://localhost:8080
tags:
  - name: superhero
    description: Endpoints that allow superheroes maintenance

paths:
  /superheroes:
    get:
      tags:
        - superhero
      summary: Retrieve all the superheroes
      description: Retrieve all the superheroes
      operationId: getAllSuperheroes
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SuperheroDTO'
  /superheroes/findByName:
    get:
      tags:
        - superhero
      summary: Retrieve superheroes by name
      description: Retrieve all superheroes whose name contains the parameter name
      operationId: getSuperheroesByName
      parameters:
        - name: name
          in: query
          description: The name
          required: true
          schema:
            type: string
            example: 'man'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SuperheroDTO'
  /superhero/{id}:
    get:
      tags:
        - superhero
      summary: Retrieve one superhero from an id
      description: Retrieve one superhero from an id
      operationId: getSuperheroFromId
      parameters:
        - name: id
          in: path
          description: id of superhero to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuperheroDTO'

        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
components:
  schemas:
    SuperheroDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: 'Superman'
    ErrorDTO:
      type: object
      properties:
        code:
          type: integer
        descriptionError:
          type: string